### ISSUE TITLE
Dataset provided has 21 sentence pairs but paper says 12K pairs

### ISSUE THREAD

**Issue by santhoshtr** [SaraRenG/MaNLI-data#1]
Hello,
As per the paper titled "Feature based Entailment Recognition for Malayalam Language Texts", I was expecting a huge dataset as given in the paper:

![image](https://user-images.githubusercontent.com/161672/174772641-f6721e71-a401-49d3-898f-686570565368.png)

But this repo has only 21 sentence pairs in the uploaded data.xlx file. Where can I get the actual dataset used for the research so that I can reproduce the result?
Also, these small set of sentences are using very bad translations as shown in examples below. Was this verified by linguists at Malayalam university as claimed in the paper?

* രണ്ട് ശാസ്ത്രക്രിയാകാരന്മാർ ഉച്ചഭക്ഷണത്തിലാണ്.
* ജാമീത്തിയ രീതിയിൽ ചിത്രങ്ങൾ വരച്ച ഘടന പോലെയുള്ള ഗാരേജിന് മുന്നിൽ നീല കുപ്പായം ധരിച്ച ഒരു മനുഷ്യൻ നിൽക്കുന്നു.
* ഭക്ഷണശാലയുടെ ജനലിൽ സാൻവിച്ചസ് വിളമ്പുന്ന ഒരു മുതിർന്നയാൾ കാത്തുനിൽക്കുന്നു.

**Comment by SaraRenG** [comment]
Hello Sir,
This is a sample from the dataset. Since the work is going on, we have restrictions to release the complete dataset. We have verified the data with the research students from the University. The dataset is a mix of google translations and human translations. 
Thank you

**Comment by santhoshtr** [comment]
Thanks for quick reply. Would it be difficult to provide this information somewhere in the repo - that this is just a sample of MANLI data and actual dataset is not available?

As a native Malayalam speaker I can confidently say that the translations in sample dataset is seriously mistranslated. The example sentences used in this paper "Natural language inference for Malayalam language using language agnostic sentence
representation" is also badly translated Malayalam and does not look reviewed by anybody.

Not publishing the data makes the research [non-reproducible](https://en.wikipedia.org/wiki/Replication_crisis) and nullifying the research. Please remember that your research is enabled by many open source libraries, including the indicstemmer I wrote and published in opensource. Your research was made possible because of [SNLI is available in CC license.](https://nlp.stanford.edu/projects/snli/) and put no restrictions for access.
